name: Azure Bicep Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Ensure Resource Group Exists
      run: |
        az group create --name rg-iac-lab --location eastus2 || echo "Resource group already exists"

    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v2
      with:
        scope: resourcegroup
        resourcegroupname: rg-iac-lab
        region: eastus2
        template: ./bicep/main.bicep
        parameters: ./bicep/parameters.json