name: Azure Bicep Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        region: eastus2
        template: ./bicep/main.bicep
        parameters: ./bicep/parameters.json