name: Azure Bicep Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        auth-type: SERVICE_PRINCIPAL

    - name: Deploy Bicep Template
      uses: azure/arm-deploy@v2
      with:
        scope: subscription
        template: ./bicep/main.bicep
        parameters: ./bicep/parameters.json